import Head from 'next/head' // it contains all the head element 
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className={styles.main}>
      <div className={styles.imgwrap}>
          <img className={styles.myImg} src="/homeimage.jpg" alt="homepage" width={237} height ={158} />
        </div>
        <h1 className={styles.title}>
          <span className={styles.dummy}>&lt;HuntingCoder/&gt;</span> 
        </h1>
        <p className={styles.description}>
          A Blogs for hunting coder by a hunting coder Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui magnam aspernatur ducimus, maiores sint itaque accusamus, veritatis nam aliquam assumenda sapiente nisi dignissimos, sequi iste impedit optio atque recusandae tempore voluptas illo doloremque officia.
        </p>
      <div>
        <h2 className={styles.popularBlogH2}>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3 className={styles.blogItemH3}>How to learn javascript in 2022</h3>
            <p className={styles.blogItemP}>javascript is the language used to design the logic for the web</p>
            <button className={styles.btn}>Read More..</button>
          </div>
          <div className={styles.blogItem}>
            <h3 className={styles.blogItemH3}>How to learn javascript in 2022</h3>
            <p className={styles.blogItemP}>javascript is the language used to design the logic for the web</p>
            <button className={styles.btn}>Read More..</button>
          </div>
          <div className={styles.blogItem}>
            <h3 className={styles.blogItemH3}>How to learn javascript in 2022</h3>
            <p className={styles.blogItemP}>javascript is the language used to design the logic for the web</p>
            <button className={styles.btn}>Read More..</button>
          </div>
      </div>

      </main>

      <footer className={styles.footer}>
   
      </footer>
    </div>
  )
}
