import Head from 'next/head' // it contains all the head element 
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script' // it is use to optimize the external js script
import Link from 'next/link'
import Dummy from '../components/dummy'
// import styles1 from '../styles/Home1.module.css'
// import styles2 from '../styles/Home2.module.css' 
// import ".../styles/style" // not able to use global css in nextjs local component expect app component
// we can use module base css file in js component expect app.js 
export default function Home() {
  return (
    <div className={styles.container}>
      <Dummy/>
      {/*  style jsx is the way to implement css in this component only */}
    <style jsx>
      {`
      .mySpan{
        color:red;
      }
      `}
    </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
        <Link href={'/'}> 
          <a><li>Home</li></a> 
        </Link>
          <Link href={'/about'}>
          <a><li>About</li></a>
          </Link>
          <Link href={'/blog'}>
          <a><li>Blog</li></a>
          </Link>
          <Link href={'/contact'}>
            <a><li>Contact</li></a>
          </Link>
        </ul>
      </nav>
      {/* <Script src='/sr.js'strategy="lazyOnload" ></Script> */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='mySpan dummy'>Hunting Coder</span> 
        </h1>

        <p className={styles.description}>
          A Blogs for hunting coder by a hunting coder
        </p>
      {/* <div className={`${styles1.con} ${styles2.con}`}> template literal in js */} 
      <div>
        <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn javascript in 2022</h3>
            <p>javascript is the language used to design the logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javascript in 2022</h3>
            <p>javascript is the language used to design the logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javascript in 2022</h3>
            <p>javascript is the language used to design the logic for the web</p>
          </div>
      </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
